
spring:
  data:
    mongodb:
      uri: ${uri}
      database: journaldb
      auto-index-creation: true


server:
  port: 8080
  servlet:
    context-path: /journal



weather:
  api:
    key: 572f2a2bbb2d93740d262f1d72120e04
